//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeicToPngConverter.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeicToPngConverter.Language.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出 (.edz).
        /// </summary>
        internal static string Btn_EdzExport {
            get {
                return ResourceManager.GetString("Btn_EdzExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列表.
        /// </summary>
        internal static string Btn_Listele {
            get {
                return ResourceManager.GetString("Btn_Listele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入 (.edz).
        /// </summary>
        internal static string Btn_SourceFile {
            get {
                return ResourceManager.GetString("Btn_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件找到了.
        /// </summary>
        internal static string DosyaBulundu {
            get {
                return ResourceManager.GetString("DosyaBulundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        internal static string gBox_export {
            get {
                return ResourceManager.GetString("gBox_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        internal static string gBox_import {
            get {
                return ResourceManager.GetString("gBox_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹.
        /// </summary>
        internal static string Klasor {
            get {
                return ResourceManager.GetString("Klasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件正在传输.
        /// </summary>
        internal static string Lbl_DownloadInfo {
            get {
                return ResourceManager.GetString("Lbl_DownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到0个文件。.
        /// </summary>
        internal static string Lbl_Find {
            get {
                return ResourceManager.GetString("Lbl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌：.
        /// </summary>
        internal static string Lbl_Marka {
            get {
                return ResourceManager.GetString("Lbl_Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 压缩大小：.
        /// </summary>
        internal static string Lbl_SBoyut {
            get {
                return ResourceManager.GetString("Lbl_SBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总大小：.
        /// </summary>
        internal static string Lbl_ToplamBoyut {
            get {
                return ResourceManager.GetString("Lbl_ToplamBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码：.
        /// </summary>
        internal static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件传输完成。.
        /// </summary>
        internal static string msg1_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string msg1_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件未找到。.
        /// </summary>
        internal static string msg2_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string msg2_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入品牌信息。.
        /// </summary>
        internal static string msgMarka {
            get {
                return ResourceManager.GetString("msgMarka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序已经在运行中...!.
        /// </summary>
        internal static string ProgramControl {
            get {
                return ResourceManager.GetString("ProgramControl", resourceCulture);
            }
        }
    }
}
